name: Update base docker image

on:
  workflow_dispatch:
  workflow_call:

env:
  AZ_RESOURCE_GROUP: rg-fooz-tournaments
  AZ_LOCATION: norwayeast
  AZ_STORAGE_NAME: stbicep99anoeast
  AZ_STORAGE_CONTAINER_NAME: hashfile
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  BASE_IMAGE_NAME: fooz/client.base

jobs:
  compare-hash:
    runs-on: ubuntu-latest
    outputs:
      isEqual: ${{ steps.compare.outputs.isEqual }}

    steps:
      - uses: actions/checkout@v3
      - id: compare
        run: bash ./foozInfra/scripts/comparePackageFile.sh
        env:
          BRANCH_NAME: ${{ github.ref_name }}

  build-if-needed:
    runs-on: ubuntu-latest
    needs: compare-hash
    if: ${{ needs.compare-hash.outputs.isEqual }} == 'false'
    steps:
      - uses: actions/checkout@v3
      - name: build  base docker image
        working-directory: ./remix-app
        run: docker build . --file Dockerfile.base --tag ronhaland.azurecr.io/${{ env.BASE_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Connect to container registry
        run: |
          az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID" || (echo -e "\n\nFailed to log in to Azure."; exit 1)
          az acr login --name ronhaland

      - name: Push image
        run: docker push ronhaland.azurecr.io/${{ env.BASE_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Update hash file
        run: bash ./foozInfra/scripts/refreshPackageHash.sh
        env:
          BRANCH_NAME: ${{ github.ref_name }}
