name: Deploy TEST environment

on:
  workflow_dispatch:

jobs:
  deploy-api:
    uses: ./.github/workflows/build-and-deploy-rpi.yml
    with:
      environment: TEST
    secrets: inherit

  deploy-client:
    uses: ./.github/workflows/build-and-deploy-client-rpi.yml
    with:
      environment: TEST
    secrets: inherit
